# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/hexad/Documents/Artix-7/UART/UART.srcs/sources_1/bd/uart_proc/ip/uart_proc_microblaze_mcs_0_0/uart_proc_microblaze_mcs_0_0.xci
# IP: The module: 'uart_proc_microblaze_mcs_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/hexad/Documents/Artix-7/UART/UART.gen/sources_1/bd/uart_proc/ip/uart_proc_microblaze_mcs_0_0/bd_0/bd_0c38.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0c38 || ORIG_REF_NAME==bd_0c38} -quiet] -quiet

# IP: c:/Users/hexad/Documents/Artix-7/UART/UART.gen/sources_1/bd/uart_proc/ip/uart_proc_microblaze_mcs_0_0/bd_0/ip/ip_0/bd_0c38_microblaze_I_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0c38_microblaze_I_0 || ORIG_REF_NAME==bd_0c38_microblaze_I_0} -quiet] -quiet

# IP: c:/Users/hexad/Documents/Artix-7/UART/UART.gen/sources_1/bd/uart_proc/ip/uart_proc_microblaze_mcs_0_0/bd_0/ip/ip_1/bd_0c38_rst_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0c38_rst_0_0 || ORIG_REF_NAME==bd_0c38_rst_0_0} -quiet] -quiet

# IP: c:/Users/hexad/Documents/Artix-7/UART/UART.gen/sources_1/bd/uart_proc/ip/uart_proc_microblaze_mcs_0_0/bd_0/ip/ip_2/bd_0c38_ilmb_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0c38_ilmb_0 || ORIG_REF_NAME==bd_0c38_ilmb_0} -quiet] -quiet

# IP: c:/Users/hexad/Documents/Artix-7/UART/UART.gen/sources_1/bd/uart_proc/ip/uart_proc_microblaze_mcs_0_0/bd_0/ip/ip_3/bd_0c38_dlmb_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0c38_dlmb_0 || ORIG_REF_NAME==bd_0c38_dlmb_0} -quiet] -quiet

# IP: c:/Users/hexad/Documents/Artix-7/UART/UART.gen/sources_1/bd/uart_proc/ip/uart_proc_microblaze_mcs_0_0/bd_0/ip/ip_4/bd_0c38_dlmb_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0c38_dlmb_cntlr_0 || ORIG_REF_NAME==bd_0c38_dlmb_cntlr_0} -quiet] -quiet

# IP: c:/Users/hexad/Documents/Artix-7/UART/UART.gen/sources_1/bd/uart_proc/ip/uart_proc_microblaze_mcs_0_0/bd_0/ip/ip_5/bd_0c38_ilmb_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0c38_ilmb_cntlr_0 || ORIG_REF_NAME==bd_0c38_ilmb_cntlr_0} -quiet] -quiet

# IP: c:/Users/hexad/Documents/Artix-7/UART/UART.gen/sources_1/bd/uart_proc/ip/uart_proc_microblaze_mcs_0_0/bd_0/ip/ip_6/bd_0c38_lmb_bram_I_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0c38_lmb_bram_I_0 || ORIG_REF_NAME==bd_0c38_lmb_bram_I_0} -quiet] -quiet

# IP: c:/Users/hexad/Documents/Artix-7/UART/UART.gen/sources_1/bd/uart_proc/ip/uart_proc_microblaze_mcs_0_0/bd_0/ip/ip_7/bd_0c38_iomodule_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0c38_iomodule_0_0 || ORIG_REF_NAME==bd_0c38_iomodule_0_0} -quiet] -quiet

# XDC: c:/Users/hexad/Documents/Artix-7/UART/UART.gen/sources_1/bd/uart_proc/ip/uart_proc_microblaze_mcs_0_0/bd_0/ip/ip_0/bd_0c38_microblaze_I_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0c38_microblaze_I_0 || ORIG_REF_NAME==bd_0c38_microblaze_I_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/hexad/Documents/Artix-7/UART/UART.gen/sources_1/bd/uart_proc/ip/uart_proc_microblaze_mcs_0_0/bd_0/ip/ip_0/bd_0c38_microblaze_I_0_ooc_debug.xdc

# XDC: c:/Users/hexad/Documents/Artix-7/UART/UART.gen/sources_1/bd/uart_proc/ip/uart_proc_microblaze_mcs_0_0/bd_0/ip/ip_1/bd_0c38_rst_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0c38_rst_0_0 || ORIG_REF_NAME==bd_0c38_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/hexad/Documents/Artix-7/UART/UART.gen/sources_1/bd/uart_proc/ip/uart_proc_microblaze_mcs_0_0/bd_0/ip/ip_1/bd_0c38_rst_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0c38_rst_0_0 || ORIG_REF_NAME==bd_0c38_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/hexad/Documents/Artix-7/UART/UART.gen/sources_1/bd/uart_proc/ip/uart_proc_microblaze_mcs_0_0/bd_0/ip/ip_3/bd_0c38_dlmb_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0c38_dlmb_0 || ORIG_REF_NAME==bd_0c38_dlmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/hexad/Documents/Artix-7/UART/UART.gen/sources_1/bd/uart_proc/ip/uart_proc_microblaze_mcs_0_0/bd_0/ip/ip_6/bd_0c38_lmb_bram_I_0_ooc.xdc

# XDC: c:/Users/hexad/Documents/Artix-7/UART/UART.gen/sources_1/bd/uart_proc/ip/uart_proc_microblaze_mcs_0_0/bd_0/ip/ip_7/bd_0c38_iomodule_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0c38_iomodule_0_0 || ORIG_REF_NAME==bd_0c38_iomodule_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/hexad/Documents/Artix-7/UART/UART.gen/sources_1/bd/uart_proc/ip/uart_proc_microblaze_mcs_0_0/bd_0/bd_0c38_ooc.xdc

# XDC: c:/Users/hexad/Documents/Artix-7/UART/UART.gen/sources_1/bd/uart_proc/ip/uart_proc_microblaze_mcs_0_0/uart_proc_microblaze_mcs_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart_proc_microblaze_mcs_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/hexad/Documents/Artix-7/UART/UART.gen/sources_1/bd/uart_proc/ip/uart_proc_microblaze_mcs_0_0/uart_proc_microblaze_mcs_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart_proc_microblaze_mcs_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/hexad/Documents/Artix-7/UART/UART.srcs/sources_1/bd/uart_proc/ip/uart_proc_microblaze_mcs_0_0/uart_proc_microblaze_mcs_0_0.xci
# IP: The module: 'uart_proc_microblaze_mcs_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/hexad/Documents/Artix-7/UART/UART.gen/sources_1/bd/uart_proc/ip/uart_proc_microblaze_mcs_0_0/bd_0/bd_0c38.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0c38 || ORIG_REF_NAME==bd_0c38} -quiet] -quiet

# IP: c:/Users/hexad/Documents/Artix-7/UART/UART.gen/sources_1/bd/uart_proc/ip/uart_proc_microblaze_mcs_0_0/bd_0/ip/ip_0/bd_0c38_microblaze_I_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0c38_microblaze_I_0 || ORIG_REF_NAME==bd_0c38_microblaze_I_0} -quiet] -quiet

# IP: c:/Users/hexad/Documents/Artix-7/UART/UART.gen/sources_1/bd/uart_proc/ip/uart_proc_microblaze_mcs_0_0/bd_0/ip/ip_1/bd_0c38_rst_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0c38_rst_0_0 || ORIG_REF_NAME==bd_0c38_rst_0_0} -quiet] -quiet

# IP: c:/Users/hexad/Documents/Artix-7/UART/UART.gen/sources_1/bd/uart_proc/ip/uart_proc_microblaze_mcs_0_0/bd_0/ip/ip_2/bd_0c38_ilmb_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0c38_ilmb_0 || ORIG_REF_NAME==bd_0c38_ilmb_0} -quiet] -quiet

# IP: c:/Users/hexad/Documents/Artix-7/UART/UART.gen/sources_1/bd/uart_proc/ip/uart_proc_microblaze_mcs_0_0/bd_0/ip/ip_3/bd_0c38_dlmb_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0c38_dlmb_0 || ORIG_REF_NAME==bd_0c38_dlmb_0} -quiet] -quiet

# IP: c:/Users/hexad/Documents/Artix-7/UART/UART.gen/sources_1/bd/uart_proc/ip/uart_proc_microblaze_mcs_0_0/bd_0/ip/ip_4/bd_0c38_dlmb_cntlr_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0c38_dlmb_cntlr_0 || ORIG_REF_NAME==bd_0c38_dlmb_cntlr_0} -quiet] -quiet

# IP: c:/Users/hexad/Documents/Artix-7/UART/UART.gen/sources_1/bd/uart_proc/ip/uart_proc_microblaze_mcs_0_0/bd_0/ip/ip_5/bd_0c38_ilmb_cntlr_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0c38_ilmb_cntlr_0 || ORIG_REF_NAME==bd_0c38_ilmb_cntlr_0} -quiet] -quiet

# IP: c:/Users/hexad/Documents/Artix-7/UART/UART.gen/sources_1/bd/uart_proc/ip/uart_proc_microblaze_mcs_0_0/bd_0/ip/ip_6/bd_0c38_lmb_bram_I_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0c38_lmb_bram_I_0 || ORIG_REF_NAME==bd_0c38_lmb_bram_I_0} -quiet] -quiet

# IP: c:/Users/hexad/Documents/Artix-7/UART/UART.gen/sources_1/bd/uart_proc/ip/uart_proc_microblaze_mcs_0_0/bd_0/ip/ip_7/bd_0c38_iomodule_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0c38_iomodule_0_0 || ORIG_REF_NAME==bd_0c38_iomodule_0_0} -quiet] -quiet

# XDC: c:/Users/hexad/Documents/Artix-7/UART/UART.gen/sources_1/bd/uart_proc/ip/uart_proc_microblaze_mcs_0_0/bd_0/ip/ip_0/bd_0c38_microblaze_I_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0c38_microblaze_I_0 || ORIG_REF_NAME==bd_0c38_microblaze_I_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/hexad/Documents/Artix-7/UART/UART.gen/sources_1/bd/uart_proc/ip/uart_proc_microblaze_mcs_0_0/bd_0/ip/ip_0/bd_0c38_microblaze_I_0_ooc_debug.xdc

# XDC: c:/Users/hexad/Documents/Artix-7/UART/UART.gen/sources_1/bd/uart_proc/ip/uart_proc_microblaze_mcs_0_0/bd_0/ip/ip_1/bd_0c38_rst_0_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0c38_rst_0_0 || ORIG_REF_NAME==bd_0c38_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/hexad/Documents/Artix-7/UART/UART.gen/sources_1/bd/uart_proc/ip/uart_proc_microblaze_mcs_0_0/bd_0/ip/ip_1/bd_0c38_rst_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0c38_rst_0_0 || ORIG_REF_NAME==bd_0c38_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/hexad/Documents/Artix-7/UART/UART.gen/sources_1/bd/uart_proc/ip/uart_proc_microblaze_mcs_0_0/bd_0/ip/ip_3/bd_0c38_dlmb_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0c38_dlmb_0 || ORIG_REF_NAME==bd_0c38_dlmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/hexad/Documents/Artix-7/UART/UART.gen/sources_1/bd/uart_proc/ip/uart_proc_microblaze_mcs_0_0/bd_0/ip/ip_6/bd_0c38_lmb_bram_I_0_ooc.xdc

# XDC: c:/Users/hexad/Documents/Artix-7/UART/UART.gen/sources_1/bd/uart_proc/ip/uart_proc_microblaze_mcs_0_0/bd_0/ip/ip_7/bd_0c38_iomodule_0_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0c38_iomodule_0_0 || ORIG_REF_NAME==bd_0c38_iomodule_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/hexad/Documents/Artix-7/UART/UART.gen/sources_1/bd/uart_proc/ip/uart_proc_microblaze_mcs_0_0/bd_0/bd_0c38_ooc.xdc

# XDC: c:/Users/hexad/Documents/Artix-7/UART/UART.gen/sources_1/bd/uart_proc/ip/uart_proc_microblaze_mcs_0_0/uart_proc_microblaze_mcs_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart_proc_microblaze_mcs_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/hexad/Documents/Artix-7/UART/UART.gen/sources_1/bd/uart_proc/ip/uart_proc_microblaze_mcs_0_0/uart_proc_microblaze_mcs_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart_proc_microblaze_mcs_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
