# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/hexad/Documents/Artix-7/UART/Arty_A7_Master.xdc

# Block Designs: bd/uart_proc/uart_proc.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uart_proc || ORIG_REF_NAME==uart_proc} -quiet] -quiet

# IP: bd/uart_proc/ip/uart_proc_microblaze_mcs_0_0/uart_proc_microblaze_mcs_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uart_proc_microblaze_mcs_0_0 || ORIG_REF_NAME==uart_proc_microblaze_mcs_0_0} -quiet] -quiet

# XDC: c:/Users/hexad/Documents/Artix-7/UART/UART.gen/sources_1/bd/uart_proc/uart_proc_ooc.xdc
